services:
  front:
    build:
      context: ./front
      target: ${FRONTEND_TARGET:-production}
      args:
        - NUXT_PUBLIC_API_BASE=https://oa.cioospacificlabs.ca/api
    ports:
      - "${FRONT_PORT:-3000}:3000"
    volumes: []
    environment:
      - NUXT_PUBLIC_API_BASE=https://oa.cioospacificlabs.ca/api
    # depends_on:
    #   - api
    command: ${FRONTEND_COMMAND:-npm run start}
    restart: unless-stopped

  api:
    build: ./api
    ports:
      - "${API_PORT:-4000}:4000"
    volumes:
      - ./data:/opt/data
      # - ./lib:/app/lib
      # - ./bathymetry_images:/app/bathymetry_images
      # - ./trajectory_maps:/app/trajectory_maps
    environment:
      - DB_HOST=db
      - DB_NAME=oa
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgis/postgis:16-master
    environment:
      - POSTGRES_DB=oa
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - oa_db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  process:
    build: ./process
    # profiles: ["tools"]
    environment:
      - PGHOST=db
      - PGPORT=5432  # default Postgres port inside the Docker network
      - PGDATABASE=oa
      - PGUSER=postgres
      - PGPASSWORD=postgres
    volumes:
      # - ./lib:/app/lib
      - ./data:/opt/data
    depends_on:
      db:
        condition: service_healthy

volumes:
  oa_db: