services:
  front:
    build:
      target: development
    volumes:
      - ./front:/app
    environment:
      - NUXT_PUBLIC_API_BASE=http://localhost:9001
    env_file:
      - .env.dev
    command: npm run dev
  api:
    command: uvicorn server:app --reload --host 0.0.0.0 --port 4000
    volumes:
      - ./api:/app
  process:
    volumes:
      - ./process:/app
