services:
  db:
    build: .
    container_name: my-ch-env
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_logs:/var/log/clickhouse-server
      # - ./data:/app/data
      - /media/taimaz/CIOOS/data:/app/data
      - ./scripts:/app/scripts
      - ./clickhouse-entrypoint.sh:/app/clickhouse-entrypoint.sh
    environment:
      CLICKHOUSE_PASSWORD: "${CLICKHOUSE_PASSWORD:-}"
    restart: unless-stopped
